!!com.ryu.encrypt.miner.proxy.model.configs.SyncToClientFileConfig
brandName: UU7rs1pJUuLVcj2y9LnQ8Q==
clientDownload: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
logo: null
mode: 7Yzq/gOqhiLTi+DwLNTxdw==
notice: wPJhbfKKhdcVj3tNVHjeKMS88u8YHBN3eAVLjeHKSyU=
qq: WksKtxYLih6s8z13VQNszQ==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
syncServer: IGLBRZ0fckGa4MSxRtU7p4KFCelJISEgEEfMEG3RDLo=
syncToClientServerConf:
- coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  serverProxy: 3aUsz7JhOWdyL/jX7lwPcH6lwbTe8p8GFAMLReSuyfo=
  serverProxyAlias: HTAIsFYmEMqxAACCTzhIXA==
- coin: yP+lgd7Lkxkn/iiR7yaU6w==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  serverProxy: CBTbPZacrG34UiI12+ICYMlauBnmYJaegBNxBjcAcM4=
  serverProxyAlias: WXVKqTgAlhwQDsWmOH0Szw==
telegram: 7ZBFyrSfEqDU3/+O4CfurByMVZiM9rArdz8A6Z8TZuc=
tutorial: LjVREpYNVA0X9EQDBix7IwqQ+3DhPtIfy2hVu53zzdI=
version: Qz3oi9qPsvsgaFWTfrAPaA==
