!!com.ryu.encrypt.miner.proxy.client.model.ClientProxyFileConfig
clientLocal: 9r0Omq7KFoS7oEc5rvqTiA==
clientProxys: []
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
mode: 7Yzq/gOqhiLTi+DwLNTxdw==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
version: Qz3oi9qPsvsgaFWTfrAPaA==
webLoginName: null
webPassword: null
