!!com.ryu.encrypt.miner.proxy.server.model.configs.ServerProxyFileConfig
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
minerDirectToServer: tccWrnbRj7ewMLNl9oVahA==
mode: EW/4By3wLrF16VbzXXpaCw==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
serverProxys:
- brokerFee: T6XdDwh11lsYOnMk1nxf8w==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: SqQy9VZt1i9SwAt2wxjlZg==
  coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: g49MCNUl8k1Z1eFCtqkgHA==
  localPortAlias: UoljFfPuYySTtBDZ6OMBFQ==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: ZnqDb+kEFVIdkaIKEbBukbcmCxno+/FHxYciJap1wUg8tPnSYUgNW4+i+jQ7fINu
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: gmd8FrvylLXifj2NBFuYaQ==
  coin: AMJqusM9exWvY/0yJ6Sniw==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: KouGRu3HrmMIXXSdlPEq+w==
  localPortAlias: +ML7pkysNaIX4Iy3sq7ipA==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: WNySricJozUG99tm28O63w==
  minerPool: P1NX8l3BsOq2hYHAwZ+fNlbXL3bGjFor1gP4jIMzzWola8ks4F5vXFc+J61rHUsA
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: yUotO+MrpTy8nyuOqGX96dZHVDNR188KXQZMSYkGc/Aur0nG4RzW1XVoSLyOoEgd
  coin: sRqeC96xW5gI/sXLzPSZmg==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: bKQ0lZY76bZVc1/Oh+8qzw==
  localPortAlias: BGKF0y32ZX8I38v6iyDe8D8OZAZB+KAMIRycmzROpEM=
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: VlG3I1ubNSbgO/mBwi1rPXqxhJ0QsIsHb+MKK3SMEnRHg7oHp3/O20BoXPh7HlXG
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: Oju5U58mLTIdKXwXLEtyWIjyR1TSYcXXF0uhXS6iwRtxtnE7G2C6l0g48OVjht+x
  coin: yP+lgd7Lkxkn/iiR7yaU6w==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: AHdJysQCULbPAreAo/de1Q==
  localPortAlias: jXJ67rMoWYNrizQ4/q1MwQ==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: VlG3I1ubNSbgO/mBwi1rPWyUiP3aPikFal5zUeTBhGlTp5GzI5vdBUggdCdwfFYG
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: SqQy9VZt1i9SwAt2wxjlZg==
  coin: /22U42B6CZyMtKFjylS14w==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: lg4YXU83N/FCifssKMZFJQ==
  localPortAlias: 2aMiqUQg33oQzNsu2C8dGw==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: fgRc4MBfIxudh3rtd/r9IHjO9MhqCui+lfWqYajUNT/0+JezVq/kFaemQ3wJ1ZX1
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: SqQy9VZt1i9SwAt2wxjlZg==
  coin: z3ouobTT7889PjBAssLIfg==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: f+8QvxNYPlNYeUSvhPaljA==
  localPortAlias: 8XPSzejQOswyey5B8oGZew==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: JDBbCmp5lOG1czFJHU2TqCU9Y531MhWFAML8oy3rWTQl8ALilWbb+NLI3Tt8JrI0
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: cALkv9jbNLBc6EcdnghmkwyLIrAwufLp+eUka1T2nCAaxLw+xt36BeEdYuo17DWh
  coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: pKaDke/gMBSVpCebX1UITw==
  localPortAlias: wCPiDUd6WwHyGGZaFZCUMg==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: ZnqDb+kEFVIdkaIKEbBukaQLUm4IHeIXmaslCq0RGSSVWa9D/Y3jXmIht8YXPmev
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: cALkv9jbNLBc6EcdnghmkwyLIrAwufLp+eUka1T2nCAaxLw+xt36BeEdYuo17DWh
  coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: b/R4X7j1YX5x9RvtxPDw2A==
  localPortAlias: Q08kC6GVgCHkGHVSWtR0QxaN5Kpx8OmbtdpmKCg9jTo=
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: VlG3I1ubNSbgO/mBwi1rPf0FrABkcfuiLyCbw8A5uQ3+Q6gGPVxV781aTri6tSl5
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: csUxilAlsQamM5nZRqh9Qw==
  coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: KouGRu3HrmMIXXSdlPEq+w==
  localPortAlias: fmh8REh6N1uOUcm3eeLPhg==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: ZnqDb+kEFVIdkaIKEbBukXOG5o5F0O26vvXEfHYfSajD/NZXMpLaPW8vr0NvD7qS
- brokerFee: pVrCR5FpQ7Uf34IZMgd1Vw==
  brokerName: RZRVLitXcXMbhlvD3BS+yQ==
  brokerWallet: Ho4m3cwCSKOJASu/Cp8Rrg==
  coin: sRqeC96xW5gI/sXLzPSZmg==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: ct4ll2kml6Mb9J9xNxOVPQ==
  localPortAlias: auaYFT7/iKrIJ2sYpP1SdQ==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  minerPool: mUzAWIKdbBpL+tAYGN89eEITz02c0xfXRgYQri+QN412jkbOJTSeRkYBCnjB8pSo
version: Qz3oi9qPsvsgaFWTfrAPaA==
webLoginName: KHA4GWCGcFXfjnlWkDrEpQ==
webPassword: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
