!!com.ryu.encrypt.miner.proxy.model.conf.SyncToClientAllConfig
brandName: /hmhoi5h1XuedvsYDVENlg==
clientDownLoad: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
logo: null
mode: 7Yzq/gOqhiLTi+DwLNTxdw==
notice: wPJhbfKKhdcVj3tNVHjeKMS88u8YHBN3eAVLjeHKSyU=
qq: WksKtxYLih6s8z13VQNszQ==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
syncServer: Xo9vZyHp9V3GazM1GT7Pw/yPWKii+bwrEdZkmjUtum0=
syncToClientServerConf:
- coin: uwS28/G/wCoKcT59ovE6BA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  serverProxy: VPl1QHF9CCZ2pIEMZ6r/g7AK6Uol3Wr1khHeNGidZRQ=
  serverProxyAlias: HTAIsFYmEMqxAACCTzhIXA==
  serverProxyHost: null
  serverProxyPort: null
- coin: yP+lgd7Lkxkn/iiR7yaU6w==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  serverProxy: TmFpQDKUfPafv+3iff/pp0AiMIzZAJ2Xlj7eLcCvI/Y=
  serverProxyAlias: WXVKqTgAlhwQDsWmOH0Szw==
  serverProxyHost: null
  serverProxyPort: null
telegram: 7ZBFyrSfEqDU3/+O4CfurByMVZiM9rArdz8A6Z8TZuc=
tutorial: LjVREpYNVA0X9EQDBix7IwqQ+3DhPtIfy2hVu53zzdI=
version: rSxEvIBBPHvxn9882cpBBg==
