!!com.ryu.encrypt.miner.proxy.model.configs.SyncToClientFileConfig
brandName: UU7rs1pJUuLVcj2y9LnQ8Q==
clientDownload: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
logo: null
mode: 7Yzq/gOqhiLTi+DwLNTxdw==
notice: wPJhbfKKhdcVj3tNVHjeKMS88u8YHBN3eAVLjeHKSyU=
qq: WksKtxYLih6s8z13VQNszQ==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
syncServer: Zlu8bQG8IibHmR22Pe7cri6HSJ+XITJmW07DvfuasuE=
syncToClientServerConf: []
telegram: 7ZBFyrSfEqDU3/+O4CfurByMVZiM9rArdz8A6Z8TZuc=
tutorial: LjVREpYNVA0X9EQDBix7IwqQ+3DhPtIfy2hVu53zzdI=
version: M6yEkpnlyxmAnt3v1VScUg==
