!!com.ryu.encrypt.miner.proxy.server.model.configs.ServerProxyFileConfig
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
minerDirectToServer: 9r0Omq7KFoS7oEc5rvqTiA==
mode: EW/4By3wLrF16VbzXXpaCw==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
serverProxys: []
version: M6yEkpnlyxmAnt3v1VScUg==
webLoginName: KHA4GWCGcFXfjnlWkDrEpQ==
webPassword: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
