!!com.ryu.encrypt.miner.proxy.server.model.userconf.ServerProxyConfig
confuse: 9r0Omq7KFoS7oEc5rvqTiA==
enableServerProxy: []
minerDirectToServer: 9r0Omq7KFoS7oEc5rvqTiA==
mode: EW/4By3wLrF16VbzXXpaCw==
secretKey: ZwRnM9c7JdXzLX4+yVSYIzfTtmLrhVPkR/I0UhOw3cIuBjl0m6VBnUAetf56rDqu
serverProxy:
- coin: uwS28/G/wCoKcT59ovE6BA==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: VlG3I1ubNSbgO/mBwi1rPf0FrABkcfuiLyCbw8A5uQ3+Q6gGPVxV781aTri6tSl5
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: cALkv9jbNLBc6EcdnghmkwyLIrAwufLp+eUka1T2nCAaxLw+xt36BeEdYuo17DWh
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: g49MCNUl8k1Z1eFCtqkgHA==
  localPortAlias: UoljFfPuYySTtBDZ6OMBFQ==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: WNySricJozUG99tm28O63w==
  poolServer: ZnqDb+kEFVIdkaIKEbBukbcmCxno+/FHxYciJap1wUg8tPnSYUgNW4+i+jQ7fINu
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: uwS28/G/wCoKcT59ovE6BA==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: VlG3I1ubNSbgO/mBwi1rPf0FrABkcfuiLyCbw8A5uQ3+Q6gGPVxV781aTri6tSl5
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: yUotO+MrpTy8nyuOqGX96dZHVDNR188KXQZMSYkGc/Aur0nG4RzW1XVoSLyOoEgd
  enable: tccWrnbRj7ewMLNl9oVahA==
  localPort: rEYXy1PUzLl5DwWViQZg5A==
  localPortAlias: nd9/Xg/Uno7trZV1zIOQNw==
  localPortSSL: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  poolServer: plDrw3n65tjalQtAmKWpDUnFqsmrzBO2aY4JrKyb93i4lWUvL3VkzNjBtfC9UzY0
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: sRqeC96xW5gI/sXLzPSZmg==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: ZnqDb+kEFVIdkaIKEbBukdxfl4Vf8Gy9jbh4og/GrykyEgys6XsuZOjqQjjTZNtR
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: BTrXljuVtpKaL1vLa5ZCXWIiqS5CcHxEXuoH2tofiQgUjqMzGPbxKrZgSIQpPGcg
  enable: tccWrnbRj7ewMLNl9oVahA==
  localPort: 8PmGO68b8zPYm19G5Nretg==
  localPortAlias: 4g9ByamsAya2HwU42o1Gxg==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  poolServer: ZnqDb+kEFVIdkaIKEbBukdxfl4Vf8Gy9jbh4og/GrykyEgys6XsuZOjqQjjTZNtR
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: sRqeC96xW5gI/sXLzPSZmg==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: VlG3I1ubNSbgO/mBwi1rPXqxhJ0QsIsHb+MKK3SMEnRHg7oHp3/O20BoXPh7HlXG
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: BTrXljuVtpKaL1vLa5ZCXWIiqS5CcHxEXuoH2tofiQgUjqMzGPbxKrZgSIQpPGcg
  enable: tccWrnbRj7ewMLNl9oVahA==
  localPort: bKQ0lZY76bZVc1/Oh+8qzw==
  localPortAlias: BGKF0y32ZX8I38v6iyDe8D8OZAZB+KAMIRycmzROpEM=
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: sA3fJhT/1L7TQd+UvdxOsw==
  poolServer: VlG3I1ubNSbgO/mBwi1rPXqxhJ0QsIsHb+MKK3SMEnRHg7oHp3/O20BoXPh7HlXG
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: AMJqusM9exWvY/0yJ6Sniw==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: P1NX8l3BsOq2hYHAwZ+fNuqPu+d5m6K3Jt9eUCRj5CnFPTjgB7wDsZje2vRBvGsR
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: O1QGratGIJHfnj6DUgWcGA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: Qk9s5vljtOm5sSXIDuSWWA==
  localPortAlias: jCbovqDbM5N/oLB2KOyT+w==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: WNySricJozUG99tm28O63w==
  poolServer: P1NX8l3BsOq2hYHAwZ+fNuqPu+d5m6K3Jt9eUCRj5CnFPTjgB7wDsZje2vRBvGsR
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: uwS28/G/wCoKcT59ovE6BA==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: ZnqDb+kEFVIdkaIKEbBukbcmCxno+/FHxYciJap1wUg8tPnSYUgNW4+i+jQ7fINu
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: yUotO+MrpTy8nyuOqGX96dZHVDNR188KXQZMSYkGc/Aur0nG4RzW1XVoSLyOoEgd
  enable: tccWrnbRj7ewMLNl9oVahA==
  localPort: 501sWoBTzctqYemT3dgy6w==
  localPortAlias: BfpuRUTvc+R/goo5tkrM4opsZYmTXRcZnI16d7fkzfg=
  localPortSSL: 9r0Omq7KFoS7oEc5rvqTiA==
  machine: WNySricJozUG99tm28O63w==
  poolServer: mUzAWIKdbBpL+tAYGN89eBPU2Bs3kliO7sgXQiAX79oEPyV2AkM3abH6QwLbN+Bo
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: uwS28/G/wCoKcT59ovE6BA==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: VlG3I1ubNSbgO/mBwi1rPf0FrABkcfuiLyCbw8A5uQ3+Q6gGPVxV781aTri6tSl5
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: yUotO+MrpTy8nyuOqGX96dZHVDNR188KXQZMSYkGc/Aur0nG4RzW1XVoSLyOoEgd
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: VgXmSXRiJailTNsN5FGMzg==
  localPortAlias: WnyacpezmTznh61kD9boOw==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: WNySricJozUG99tm28O63w==
  poolServer: ZnqDb+kEFVIdkaIKEbBukRoMAUGO5gB9H0HexI/Itv/nAOwHcN4gcV95XziH5kn/
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
- coin: AMJqusM9exWvY/0yJ6Sniw==
  devFee: 4Q3ta+DxyX8vrH2Ta9ejhA==
  devMiner: RZRVLitXcXMbhlvD3BS+yQ==
  devPool: P1NX8l3BsOq2hYHAwZ+fNuqPu+d5m6K3Jt9eUCRj5CnFPTjgB7wDsZje2vRBvGsR
  devPoolHost: null
  devPoolPort: null
  devPoolSchema: null
  devWallet: O1QGratGIJHfnj6DUgWcGA==
  enable: 9r0Omq7KFoS7oEc5rvqTiA==
  localPort: 7Pm9e29QoIcQlglT/4wZeQ==
  localPortAlias: 7Pm9e29QoIcQlglT/4wZeQ==
  localPortSSL: tccWrnbRj7ewMLNl9oVahA==
  machine: WNySricJozUG99tm28O63w==
  poolServer: mUzAWIKdbBpL+tAYGN89eFCV/om7Ikl5W1L2CO2GA/2fCOC6ly3nv70leZn9EX76
  poolServerHost: null
  poolServerPort: null
  poolServerSchema: null
version: D3Dzs8BCKTjQBcFRpw1JvA==
webLoginName: KHA4GWCGcFXfjnlWkDrEpQ==
webPassword: za2Z6vD5+UT/JUDGfZAwl5PLXmmtf/2+JAR8VAsQnSw3DDjcxeSGhzSGWPk+0RBu
